name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-latest"]
        swift-version: ["5.10", "6.0", "6.1"]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      

      - name: Install Swift and SwiftPM
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ matrix.swift-version }}
      
      - name: Get Swift version
        run: swift --version
      
      - name: Build
        run: swift build

#      - name: Run tests
#        run: swift test
